apiVersion: v1
kind: Service
metadata:
  name: {{ include "eks-arc-runner-platform.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eks-arc-runner-platform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "eks-arc-runner-platform.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
