apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arc-runners

resources:
  - namespace.yaml
  - rbac.yaml
  - runner-deployment.yaml
  - horizontal-runner-autoscaler.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  Project: eks-arc-runner-platform

commonAnnotations:
  managed-by: udap
